CREATE OR REPLACE TRIGGER "SYSTEM"."FACTURA_TRG"
  BEFORE INSERT ON  "SYSTEM"."FACTURAS" FOR EACH ROW
 WHEN (new.IDFACTURA is null)
  begin
SELECT FACTURA_SEQUENCE.NEXTVAL
  INTO :new.IDFACTURA
  FROM dual;
END;


