create or replace NONEDITIONABLE TRIGGER "SYSTEM"."PRODUCTOS_TRG"
  BEFORE INSERT ON  "SYSTEM"."PRODUCTOS" FOR EACH ROW
 WHEN (new.IDPRODUCTO is null)
  begin
SELECT PRODUCTO_SEQUENCE.NEXTVAL
  INTO :new.IDPRODUCTO
  FROM dual;
END;